
version: '3.0'

services:
  chroma:
    image: ghcr.io/socialgouv/docker/chroma:0.3.21
    # ports: 
    #   - 8000:8000
    volumes:
      - index_data:/index_data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LLAMA_MODEL: /goinfre/models/llama/13B/ggml-model-q4_0.bin
      DIRECTORY_PATH: /goinfre/data/socialgouv-support
      CHROMA_URL: http://chroma:8000
    ports:
      - 3000:3000

volumes:
  index_data: