app:
  containerPort: 3000
  ~needs: [build-app]
  probesPath: /api/healthz
  env:
    - name: LLAMA_MODEL
      value: /goinfre/models/llama/13B/ggml-model-q4_0.bin
    - name: DIRECTORY_PATH
      value: /goinfre/data
    - name: CHROMA_URL
      value: http://chroma
  volumes:
    - name: goinfre
      csi:
        driver: file.csi.azure.com
        readOnly: false
        volumeAttributes:
          secretName: azure-sre-goinfre-volume
          shareName: goinfre
  volumeMounts:
    - name: goinfre
      mountPath: /goinfre

chroma:
  ~chart: app
  image: ghcr.io/socialgouv/docker/chroma:0.3.21
  containerPort: 8000
  probesPath: /api/v1
  ingress:
    enabled: false

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          COMMIT_SHA: "{{ $.Values.global.sha }}"
